package com.termux.app.installer;

import com.termux.shared.errors.Errno;

/**
 * {@link Errno} definitions specific to the install/storage transaction layer.
 *
 * <p>Follows the {@link com.termux.shared.file.FileUtilsErrno} pattern: a unique {@link #TYPE} and a
 * non-colliding code range (1000+) so these register distinctly in the shared {@link Errno} map.
 * Filesystem-level failures are surfaced as {@link com.termux.shared.file.FileUtilsErrno} errors by
 * the {@link InstallEnvironment} filesystem operations; the codes here cover the
 * installer-specific failures generated by the steps and the coordinator.
 */
public class InstallationErrno extends Errno {

    public static final String TYPE = "Installation Error";

    public static final Errno ERRNO_STEP_EXECUTION_FAILED = new Errno(TYPE, 1000, "Install step \"%1$s\" failed with an exception.\nException: %2$s");
    public static final Errno ERRNO_ZIP_LOAD_FAILED = new Errno(TYPE, 1001, "Loading the bootstrap zip failed.\nException: %1$s");
    public static final Errno ERRNO_EXTRACTING_BOOTSTRAP_FAILED = new Errno(TYPE, 1002, "Extracting the bootstrap zip to staging directory \"%1$s\" failed.\nException: %2$s");
    public static final Errno ERRNO_MALFORMED_SYMLINK_LINE = new Errno(TYPE, 1003, "Malformed symlink line in SYMLINKS.txt: \"%1$s\".");
    public static final Errno ERRNO_NO_SYMLINKS_FOUND = new Errno(TYPE, 1004, "No SYMLINKS.txt encountered in the bootstrap zip.");
    public static final Errno ERRNO_SYMLINK_CREATION_FAILED = new Errno(TYPE, 1005, "Creating symlink at \"%1$s\" pointing to \"%2$s\" failed.\nException: %3$s");
    public static final Errno ERRNO_CHMOD_FAILED = new Errno(TYPE, 1006, "Setting executable permission on \"%1$s\" failed.\nException: %2$s");
    public static final Errno ERRNO_PREFIX_COMMIT_FAILED = new Errno(TYPE, 1007, "Moving staging directory \"%1$s\" to prefix directory \"%2$s\" failed.");

    InstallationErrno(final String type, final int code, final String message) {
        super(type, code, message);
    }
}
